const fs = require('node:fs');
const path = require('node:path');
const zlib = require('node:zlib');
const root = path.resolve(__dirname, '..');
const assets = [['index.html', 'INDEX'], ['style.css', 'STYLE'], ['script.js', 'SCRIPT']];
let output = '// Generated by npm run build:esp32. Do not edit.\n#pragma once\n#include <Arduino.h>\n';
for (const [file, name] of assets) {
  const bytes = zlib.gzipSync(fs.readFileSync(path.join(root, 'public', file)));
  output += `const uint8_t ASSET_${name}[] PROGMEM = {${Array.from(bytes).join(',')}};\n`;
}
fs.writeFileSync(path.join(root, 'arduino/EstacionamentoServidor/web_assets.h'), output);
console.log('Painel compactado e incorporado ao firmware ESP32.');
